version: '3'

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "p0stgr3s"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres-network
      
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "5000:80"
    depends_on:
      - postgresdb
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge